# encoding: UTF-8

from myquant.utils import globalSetting

lang = globalSetting['language']

__all__ = ["ABOUT", "ACCOUNT", "ACCOUNT_ID", "APPLICATION", "ASK_1", "ASK_2", "ASK_3", "ASK_4",
           "ASK_5", "ASK_PRICE_1", "ASK_PRICE_2", "ASK_PRICE_3", "ASK_PRICE_4", "ASK_PRICE_5",
           "ASK_VOLUME_1", "ASK_VOLUME_2", "ASK_VOLUME_3", "ASK_VOLUME_4", "ASK_VOLUME_5", "AVAILABLE",
           "BALANCE", "BID_1", "BID_2", "BID_3", "BID_4", "BID_5", "BID_PRICE_1", "BID_PRICE_2",
           "BID_PRICE_3", "BID_PRICE_4", "BID_PRICE_5", "BID_VOLUME_1", "BID_VOLUME_2", "BID_VOLUME_3",
           "BID_VOLUME_4", "BID_VOLUME_5", "CANCEL_ALL", "CANCEL_TIME", "CLOSE_PROFIT", "COMMISSION",
           "CONFIRM_EXIT", "CONNECT", "CONNECT_DATABASE", "CONTENT", "CONTRACT_NAME", "CONTRACT_SEARCH",
           "CONTRACT_SIZE", "CONTRACT_SYMBOL", "CPU_MEMORY_INFO", "CTA_STRATEGY", "CURRENCY",
           "DATABASE_CONNECTING_COMPLETED", "DATABASE_CONNECTING_FAILED", "DATA_INSERT_FAILED",
           "DATA_QUERY_FAILED", "DATA_RECORDER", "DATA_UPDATE_FAILED", "DIRECTION", "EDIT_SETTING",
           "ERROR", "ERROR_CODE", "ERROR_MESSAGE", "EXCHANGE", "EXIT", "EXPIRY_DATE", "FRONT_ID",
           "FROZEN", "GATEWAY", "GATEWAY_NOT_EXIST", "HELP", "HIGH_PRICE", "LAST", "LAST_PRICE",
           "LOAD", "LOG", "LOW_PRICE", "MARGIN", "MARKET_DATA", "OFFSET", "OPEN_INTEREST", "OPEN_PRICE",
           "OPTION_TYPE", "ORDER", "ORDER_ID", "ORDER_STATUS", "ORDER_TIME", "ORDER_VOLUME", "POSITION",
           "POSITION_PROFIT", "PRE_BALANCE", "PRE_CLOSE_PRICE", "PRICE", "PRICE_TICK", "PRICE_TYPE",
           "PRODUCT_CLASS", "REFRESH", "RESIZE_COLUMNS", "RESTORE", "RISK_MANAGER", "SAVE", "SAVE_DATA",
           "SEARCH", "SEND_ORDER", "SESSION_ID", "STRATEGY", "STRIKE_PRICE", "SYSTEM", "TEST", "TIME",
           "TRADE", "TRADED_VOLUME", "TRADE_ID", "TRADE_TIME", "TRADING", "UNDERLYING_SYMBOL", "VOLUME",
           "VT_SYMBOL", "WORKING_ORDER", "YD_POSITION"]

ABOUT = u'About' if lang == 'english' else u'关于'
ACCOUNT = u'Account' if lang == 'english' else u'账户'
ACCOUNT_ID = u'Account ID' if lang == 'english' else u'账户编号'
APPLICATION = u'Application' if lang == 'english' else u'功能'
ASK_1 = u'Ask1' if lang == 'english' else u'卖一'
ASK_2 = u'Ask2' if lang == 'english' else u'卖二'
ASK_3 = u'Ask3' if lang == 'english' else u'卖三'
ASK_4 = u'Ask4' if lang == 'english' else u'卖四'
ASK_5 = u'Ask5' if lang == 'english' else u'卖五'
ASK_PRICE_1 = u'Ask Price 1' if lang == 'english' else u'卖一价'
ASK_PRICE_2 = u'Ask Price 2' if lang == 'english' else u'卖二价'
ASK_PRICE_3 = u'Ask Price 3' if lang == 'english' else u'卖三价'
ASK_PRICE_4 = u'Ask Price 4' if lang == 'english' else u'卖四价'
ASK_PRICE_5 = u'Ask Price 5' if lang == 'english' else u'卖五价'
ASK_VOLUME_1 = u'Ask Volume 1' if lang == 'english' else u'卖一量'
ASK_VOLUME_2 = u'Ask Volume 2' if lang == 'english' else u'卖二量'
ASK_VOLUME_3 = u'Ask Volume 3' if lang == 'english' else u'卖三量'
ASK_VOLUME_4 = u'Ask Volume 4' if lang == 'english' else u'卖四量'
ASK_VOLUME_5 = u'Ask Volume 5' if lang == 'english' else u'卖五量'
AVAILABLE = u'Available' if lang == 'english' else u'可用'
BALANCE = u'Balance' if lang == 'english' else u'净值'
BID_1 = u'Bid1' if lang == 'english' else u'买一'
BID_2 = u'Bid2' if lang == 'english' else u'买二'
BID_3 = u'Bid3' if lang == 'english' else u'买三'
BID_4 = u'Bid4' if lang == 'english' else u'买四'
BID_5 = u'Bid5' if lang == 'english' else u'买五'
BID_PRICE_1 = u'Bid Price 1' if lang == 'english' else u'买一价'
BID_PRICE_2 = u'Bid Price 2' if lang == 'english' else u'买二价'
BID_PRICE_3 = u'Bid Price 3' if lang == 'english' else u'买三价'
BID_PRICE_4 = u'Bid Price 4' if lang == 'english' else u'买四价'
BID_PRICE_5 = u'Bid Price 5' if lang == 'english' else u'买五价'
BID_VOLUME_1 = u'Bid Volume 1' if lang == 'english' else u'买一量'
BID_VOLUME_2 = u'Bid Volume 2' if lang == 'english' else u'买二量'
BID_VOLUME_3 = u'Bid Volume 3' if lang == 'english' else u'买三量'
BID_VOLUME_4 = u'Bid Volume 4' if lang == 'english' else u'买四量'
BID_VOLUME_5 = u'Bid Volume 5' if lang == 'english' else u'买五量'
CANCEL_ALL = u'Cancel All' if lang == 'english' else u'全撤'
CANCEL_TIME = u'Cancel Time' if lang == 'english' else u'撤销时间'
CLOSE_PROFIT = u'Close Profit' if lang == 'english' else u'平仓盈亏'
COMMISSION = u'Commission' if lang == 'english' else u'手续费'
CONFIRM_EXIT = u'Confirm Exit？' if lang == 'english' else u'确认退出？'
CONNECT = u'Connect ' if lang == 'english' else u'连接'
CONNECT_DATABASE = u'Connect Database' if lang == 'english' else u'连接数据库'
CONTENT = u'Content' if lang == 'english' else u'内容'
CONTRACT_NAME = u'Name' if lang == 'english' else u'名称'
CONTRACT_SEARCH = u'Contract Search' if lang == 'english' else u'合约查询'
CONTRACT_SIZE = u'Contract Size' if lang == 'english' else u'合约大小'
CONTRACT_SYMBOL = u'Symbol' if lang == 'english' else u'合约代码'
CPU_MEMORY_INFO = u'CPU Usage：{cpu}%   Memory Usage：{memory}%' if lang == 'english' else u'CPU使用率：{cpu}%   内存使用率：{memory}%'
CTA_STRATEGY = u'CTA Strategy' if lang == 'english' else u'CTA策略'
CURRENCY = u'Currency' if lang == 'english' else u'货币'
DATABASE_CONNECTING_COMPLETED = u'MongoDB is connected.' if lang == 'english' else u'MongoDB连接成功'
DATABASE_CONNECTING_FAILED = u'Failed to connect to MongoDB.' if lang == 'english' else u'MongoDB连接失败'
DATA_INSERT_FAILED = u'Data insert failed，please connect MongoDB first.' if lang == 'english' else u'数据插入失败，MongoDB没有连接'
DATA_QUERY_FAILED = u'Data query failed, please connect MongoDB first.' if lang == 'english' else u'数据查询失败，MongoDB没有连接'
DATA_RECORDER = u'Data Recorder' if lang == 'english' else u'行情记录'
DATA_UPDATE_FAILED = u'Data update failed, please connect MongoDB first.' if lang == 'english' else u'数据更新失败，MongoDB没有连接'
DIRECTION = u'Direction' if lang == 'english' else u'方向'
EDIT_SETTING = u'Edit Setting' if lang == 'english' else u'编辑配置'
ERROR = u'Error' if lang == 'english' else u'错误'
ERROR_CODE = u'Error Code' if lang == 'english' else u'错误代码'
ERROR_MESSAGE = u'Error Message' if lang == 'english' else u'错误信息'
EXCHANGE = u'Exchange' if lang == 'english' else u'交易所'
EXIT = u'Exit' if lang == 'english' else u'退出'
EXPIRY_DATE = u'Expiry Date' if lang == 'english' else u'到期日'
FRONT_ID = u'Front ID' if lang == 'english' else u'前置编号'
FROZEN = u'Frozen' if lang == 'english' else u'冻结量'
GATEWAY = u'Gateway' if lang == 'english' else u'接口'
GATEWAY_NOT_EXIST = u"Can't find the gateway：{gateway}" if lang == 'english' else u'接口不存在：{gateway}'
HELP = u'Help' if lang == 'english' else u'帮助'
HIGH_PRICE = u'High' if lang == 'english' else u'最高价'
LAST = u'Last' if lang == 'english' else u'最新'
LAST_PRICE = u'Last' if lang == 'english' else u'最新价'
LOAD = u'Load' if lang == 'english' else u'读取'
LOG = u'Log' if lang == 'english' else u'日志'
LOW_PRICE = u'Low' if lang == 'english' else u'最低价'
MARGIN = u'Margin' if lang == 'english' else u'保证金'
MARKET_DATA = u'Market Data' if lang == 'english' else u'行情'
OFFSET = u'Offset' if lang == 'english' else u'开平'
OPEN_INTEREST = u'Open Interest' if lang == 'english' else u'持仓量'
OPEN_PRICE = u'Open' if lang == 'english' else u'开盘价'
OPTION_TYPE = u'Option Type' if lang == 'english' else u'期权类型'
ORDER = u'Order' if lang == 'english' else u'委托'
ORDER_ID = u'Order ID' if lang == 'english' else u'委托编号'
ORDER_STATUS = u'Order Status' if lang == 'english' else u'委托状态'
ORDER_TIME = u'Order Time' if lang == 'english' else u'委托时间'
ORDER_VOLUME = u'Order Volume' if lang == 'english' else u'委托数量'
POSITION = u'Position' if lang == 'english' else u'持仓'
POSITION_PROFIT = u'Position Profit' if lang == 'english' else u'持仓盈亏'
PRE_BALANCE = u'Pre Balance' if lang == 'english' else u'昨净值'
PRE_CLOSE_PRICE = u'PreClose' if lang == 'english' else u'昨收盘'
PRICE = u'Price' if lang == 'english' else u'价格'
PRICE_TICK = u'Price Tick' if lang == 'english' else u'最小价格变动'
PRICE_TYPE = u'Price Type' if lang == 'english' else u'价格类型'
PRODUCT_CLASS = u'Product Class' if lang == 'english' else u'产品类型'
REFRESH = u'Refresh' if lang == 'english' else u'刷新'
RESIZE_COLUMNS = u'Resize Columns' if lang == 'english' else u'调整列宽'
RESTORE = u'Restore Window' if lang == 'english' else u'还原窗口'
RISK_MANAGER = u'Risk Manager' if lang == 'english' else u'风控管理'
SAVE = u'Save' if lang == 'english' else u'保存'
SAVE_DATA = u'Save Data' if lang == 'english' else u'保存数据'
SEARCH = u'Search' if lang == 'english' else u'查询'
SEND_ORDER = u'Send Order' if lang == 'english' else u'发单'
SESSION_ID = u'Session ID' if lang == 'english' else u'会话编号'
STRATEGY = u'Strategy' if lang == 'english' else u'策略'
STRIKE_PRICE = u'Strike Price' if lang == 'english' else u'行权价'
SYSTEM = u'System' if lang == 'english' else u'系统'
TEST = u'Test' if lang == 'english' else u'测试'
TIME = u'Time' if lang == 'english' else u'时间'
TRADE = u'Fill' if lang == 'english' else u'成交'
TRADED_VOLUME = u'Filled Volume' if lang == 'english' else u'成交数量'
TRADE_ID = u'Fill ID' if lang == 'english' else u'成交编号'
TRADE_TIME = u'Fill Time' if lang == 'english' else u'成交时间'
TRADING = u'Trading' if lang == 'english' else u'交易'
UNDERLYING_SYMBOL = u'Underlying Symbol' if lang == 'english' else u'标的代码'
VOLUME = u'Volume' if lang == 'english' else u'成交量'
VT_SYMBOL = u'Vt System Symbol' if lang == 'english' else u'vt系统代码'
WORKING_ORDER = u'Working Order' if lang == 'english' else u'可撤'
YD_POSITION = u'Yesterday Position' if lang == 'english' else u'昨持仓'

